name: API CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16
    services:
      postgresdb:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test1234

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test:ci
        env:
          PORT: 3000
          DATABASE_URL: postgres://postgres:test1234@postgresdb:5432/testdb
          API_KEY: 79823
          JWT_SECRET: secret
          SMTP_EMAIL: your@email.com
          SMTP_PASSWORD: password-email
